import { IImage } from "../../../Utils/js/Utils";

import AboutUsJpg from "./Images/about_us.jpg";
import AdmissionsJpg from "./Images/admissions.jpg";
import ExpereinceJpg from "./Images/expereince.jpg";
import FacultyJpg from "./Images/faculty.jpg";
import GalleryJpg from "./Images/gallery.jpg";
import GalleryOneJpg from "./Images/gallery_one.jpg";
import GlobalExposureJpg from "./Images/global_exposure.jpg";
import InternationalAssociationsJpg from "./Images/international_associations.jpg";
import InternshipMotorsJpg from "./Images/internship_motors.jpg";
import LearningEnvironmentJpg from "./Images/learning_environment.jpg";
import PlacementsJpg from "./Images/placements.jpg";
import ProgramsJpg from "./Images/programs.jpg";
import TestimonialsJpg from "./Images/testimonials.jpg";
import WhyAimsIbsTwoJpg from "./Images/why_aims_ibs_2.jpg";
import WhyAimsIbsJpg from "./Images/why_aims_ibs.jpg";
import PaybannerPng from "./Images/paybanner.png";

import AboutUsWebp from "./Images/about_us.webp";
import AdmissionsWebp from "./Images/admissions.webp";
import ExpereinceWebp from "./Images/expereince.webp";
import FacultyWebp from "./Images/faculty.webp";
import GalleryWebp from "./Images/gallery.webp";
import GalleryOneWebp from "./Images/gallery_one.webp";
import GlobalExposureWebp from "./Images/global_exposure.webp";
import InternationalAssociationsWebp from "./Images/international_associations.webp";
import InternshipMotorsWebp from "./Images/internship_motors.webp";
import LearningEnvironmentWebp from "./Images/learning_environment.webp";
import PlacementsWebp from "./Images/placements.webp";
import ProgramsWebp from "./Images/programs.webp";
import TestimonialsWebp from "./Images/testimonials.webp";
import WhyAimsIbsTwoWebp from "./Images/why_aims_ibs_2.webp";
import WhyAimsIbsWebp from "./Images/why_aims_ibs.webp";
import PaybannerWebp from "./Images/paybanner.webp";


export const CommonAboutUs: IImage = {type: "jpg", alt: "", jpg: AboutUsJpg, webp: AboutUsWebp, w: 6720, h: 4480};
export const CommonAdmissions: IImage = {type: "jpg", alt: "", jpg: AdmissionsJpg, webp: AdmissionsWebp, w: 4288, h: 2848};
export const CommonExpereince: IImage = {type: "jpg", alt: "", jpg: ExpereinceJpg, webp: ExpereinceWebp, w: 5184, h: 3456};
export const CommonFaculty: IImage = {type: "jpg", alt: "", jpg: FacultyJpg, webp: FacultyWebp, w: 6720, h: 4480};
export const CommonGallery: IImage = {type: "jpg", alt: "", jpg: GalleryJpg, webp: GalleryWebp, w: 6720, h: 4480};
export const CommonGalleryOne: IImage = {type: "jpg", alt: "", jpg: GalleryOneJpg, webp: GalleryOneWebp, w: 580, h: 450};
export const CommonGlobalExposure: IImage = {type: "jpg", alt: "", jpg: GlobalExposureJpg, webp: GlobalExposureWebp, w: 1280, h: 720};
export const CommonInternationalAssociations: IImage = {type: "jpg", alt: "", jpg: InternationalAssociationsJpg, webp: InternationalAssociationsWebp, w: 5184, h: 3456};
export const CommonInternshipMotors: IImage = {type: "jpg", alt: "", jpg: InternshipMotorsJpg, webp: InternshipMotorsWebp, w: 960, h: 640};
export const CommonLearningEnvironment: IImage = {type: "jpg", alt: "", jpg: LearningEnvironmentJpg, webp: LearningEnvironmentWebp, w: 6720, h: 4480};
export const CommonPlacements: IImage = {type: "jpg", alt: "", jpg: PlacementsJpg, webp: PlacementsWebp, w: 6720, h: 4480};
export const CommonPrograms: IImage = {type: "jpg", alt: "", jpg: ProgramsJpg, webp: ProgramsWebp, w: 6720, h: 4480};
export const CommonTestimonials: IImage = {type: "jpg", alt: "", jpg: TestimonialsJpg, webp: TestimonialsWebp, w: 960, h: 720};
export const CommonWhyAimsIbsTwo: IImage = {type: "jpg", alt: "", jpg: WhyAimsIbsTwoJpg, webp: WhyAimsIbsTwoWebp, w: 6720, h: 4480};
export const CommonWhyAimsIbs: IImage = {type: "jpg", alt: "", jpg: WhyAimsIbsJpg, webp: WhyAimsIbsWebp, w: 6720, h: 4480};
export const CommonPayment: IImage = {type: "png", alt: "", png: PaybannerPng, webp: PaybannerWebp, w: 1354, h: 350};